# coding: utf-8

"""
    Caldera

    API generated by SwaggerHub Explore  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AuthLoginBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'password': 'str',
        'mobile_device_token': 'str',
        'email_address': 'str',
        'os_type': 'str',
        'location': 'str',
        'device_type': 'str'
    }

    attribute_map = {
        'password': 'password',
        'mobile_device_token': 'mobileDeviceToken',
        'email_address': 'emailAddress',
        'os_type': 'osType',
        'location': 'location',
        'device_type': 'deviceType'
    }

    def __init__(self, password=None, mobile_device_token=None, email_address=None, os_type=None, location=None, device_type=None):  # noqa: E501
        """AuthLoginBody - a model defined in Swagger"""  # noqa: E501
        self._password = None
        self._mobile_device_token = None
        self._email_address = None
        self._os_type = None
        self._location = None
        self._device_type = None
        self.discriminator = None
        self.password = password
        self.mobile_device_token = mobile_device_token
        self.email_address = email_address
        self.os_type = os_type
        self.location = location
        self.device_type = device_type

    @property
    def password(self):
        """Gets the password of this AuthLoginBody.  # noqa: E501


        :return: The password of this AuthLoginBody.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this AuthLoginBody.


        :param password: The password of this AuthLoginBody.  # noqa: E501
        :type: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password

    @property
    def mobile_device_token(self):
        """Gets the mobile_device_token of this AuthLoginBody.  # noqa: E501


        :return: The mobile_device_token of this AuthLoginBody.  # noqa: E501
        :rtype: str
        """
        return self._mobile_device_token

    @mobile_device_token.setter
    def mobile_device_token(self, mobile_device_token):
        """Sets the mobile_device_token of this AuthLoginBody.


        :param mobile_device_token: The mobile_device_token of this AuthLoginBody.  # noqa: E501
        :type: str
        """
        if mobile_device_token is None:
            raise ValueError("Invalid value for `mobile_device_token`, must not be `None`")  # noqa: E501

        self._mobile_device_token = mobile_device_token

    @property
    def email_address(self):
        """Gets the email_address of this AuthLoginBody.  # noqa: E501


        :return: The email_address of this AuthLoginBody.  # noqa: E501
        :rtype: str
        """
        return self._email_address

    @email_address.setter
    def email_address(self, email_address):
        """Sets the email_address of this AuthLoginBody.


        :param email_address: The email_address of this AuthLoginBody.  # noqa: E501
        :type: str
        """
        if email_address is None:
            raise ValueError("Invalid value for `email_address`, must not be `None`")  # noqa: E501

        self._email_address = email_address

    @property
    def os_type(self):
        """Gets the os_type of this AuthLoginBody.  # noqa: E501


        :return: The os_type of this AuthLoginBody.  # noqa: E501
        :rtype: str
        """
        return self._os_type

    @os_type.setter
    def os_type(self, os_type):
        """Sets the os_type of this AuthLoginBody.


        :param os_type: The os_type of this AuthLoginBody.  # noqa: E501
        :type: str
        """
        if os_type is None:
            raise ValueError("Invalid value for `os_type`, must not be `None`")  # noqa: E501

        self._os_type = os_type

    @property
    def location(self):
        """Gets the location of this AuthLoginBody.  # noqa: E501


        :return: The location of this AuthLoginBody.  # noqa: E501
        :rtype: str
        """
        return self._location

    @location.setter
    def location(self, location):
        """Sets the location of this AuthLoginBody.


        :param location: The location of this AuthLoginBody.  # noqa: E501
        :type: str
        """
        if location is None:
            raise ValueError("Invalid value for `location`, must not be `None`")  # noqa: E501

        self._location = location

    @property
    def device_type(self):
        """Gets the device_type of this AuthLoginBody.  # noqa: E501


        :return: The device_type of this AuthLoginBody.  # noqa: E501
        :rtype: str
        """
        return self._device_type

    @device_type.setter
    def device_type(self, device_type):
        """Sets the device_type of this AuthLoginBody.


        :param device_type: The device_type of this AuthLoginBody.  # noqa: E501
        :type: str
        """
        if device_type is None:
            raise ValueError("Invalid value for `device_type`, must not be `None`")  # noqa: E501

        self._device_type = device_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AuthLoginBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AuthLoginBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
