# coding: utf-8

"""
    Caldera

    API generated by SwaggerHub Explore  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_connextion_auth_login_post(self):
        """Test case for connextion_auth_login_post

        """
        pass

    def test_connextion_spa_my_spas_post(self):
        """Test case for connextion_spa_my_spas_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
